### ISSUE TITLE
Licensing detail

### ISSUE THREAD

**Issue by jayaddison** [dodomorandi/quadrilateral-cowboy#2]
Hi @dodomorandi - this might be pedantic, but it's probably better for me to mention it after learning about it:

Since QC is derived from the Doom3 / idTech4 engine, I think that _technically_ it's under a slight variation of the normal GPLv3 license.  Approximately: there are some additional terms applied in the license, as an overlay on top of the default GPLv3.

(boring legal stuff, I know - and the rules for that probably apply differently over time and by location.. mentioning it to help you figure out what's most worthwhile for you)

**Comment by dodomorandi** [comment]
Hi @jayaddison! Don't worry, I know that in these situations (and in many others) it is necessary to consider legal stuff :relaxed: 

For me there are no problems at all with the variation of the normal license. Let me know if I need to do something specific in order to let you avoid legal troubles.

**Comment by jayaddison** [comment]
Thanks :smile:  No changes needed that I'm aware of - I'll let you know if & when I learn of any.
